### ISSUE TITLE
Renders merge commits incorrectly?

### ISSUE THREAD

**Issue by MggMuggins** [gorhawk/git-object-visualizer#5]
For my use I only needed to render one merge commit, so it was easiest to add an edge in the `.gv` rather than dig into why the edge wasn't being drawn.

That said I thought I'd document that a commit with more than one parent didn't draw both parent relationships correctly. I haven't reproduced it due to time constraints.

EDIT: Repo that I used that didn't render correctly: https://gitlab.com/MggMuggins/example-repo

**Comment by gorhawk** [comment]
Thanks, I'll take a look. IIRC it used to work, so something happened.

**Comment by gorhawk** [comment]
I had some time to take a look and I found the problem. I need to change the combineByKeys utility function so that it creates an array of values if there are identical keys ("parent") instead of overwriting them.

**Comment by gorhawk** [comment]
fixed in [eccb1f](https://github.com/gorhawk/git-object-visualizer/commit/eccb1fde4ccf2e328eafc66c3bcc47b0df3cc965)
